language: python
python:
  - "3.9"
install:
  - pip install -r requirements.txt
before_script:
  - python ./config/manage.py makemigrations
  - python ./config/manage.py migrate --run-syncdb
script:
  - python ./config/manage.py test blog