version: '3'

networks:
  direct_net:
    external: true

services:
  web:
    build: .
    container_name: web
    env_file:
      - .env
    command: bash -c 'while !</dev/tcp/postgres/5432; do sleep 1; done; gunicorn --bind 0.0.0.0:8000 config.wsgi'
    restart: always
    ports:
      - '8010:8000'
    expose:
      - 8010
    depends_on:
      - postgres
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.django-rtr.entrypoints=https"
      - "traefik.http.routers.django-rtr.rule=Host(`$DOMAIN_NAME`)"
      ## Middlewares
      - "traefik.http.routers.django-rtr.middlewares=chain-no-auth@file"
      ## HTTP Services
      - "traefik.http.routers.django-rtr.service=django-svc"
      - "traefik.http.services.django-svc.loadbalancer.server.port=8000"
      ## Disable from watchtower
      - "com.centurylinklabs.watchtower.enable=false"
    networks:
      - direct_net

  postgres:
    image: postgres:13
    container_name: postgres
    env_file:
      - .env
    volumes:
      - ${DOCKERDIR_DB}:/var/lib/postgresql/data
    restart: always
    ports:
      - "5432:5432"
    expose:
      - 5432
    environment:
      - "POSTGRES_DB=${DATABASES_NAME}"
      - "POSTGRES_USER=${DATABASES_USER}"
      - "POSTGRES_PASSWORD=${DATABASES_PASSWORD}"
    networks:
      - direct_net

  nginx:
    image: nginx:1.15-alpine
    container_name: nginx
    env_file:
      - .env
    restart: always
    ports:
      - 80:80
    volumes:
      - ${DOCKERDIR_APP}/nginx.conf:/etc/nginx/conf.d/default.conf
      - ${DOCKERDIR_APP}/config/static:/static
      - ${DOCKERDIR_APP}/config/media:/media
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.static-http.entrypoints=https"      
      - "traefik.http.routers.static-http.rule=Host(`${DOMAIN_NAME}`) && PathPrefix(`/static`,`/media`)"
    networks:
      - direct_net
    depends_on:
      - web
