version: '3'

services:
  web:
    build: .
    env_file:
      - .env
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/site
    ports:
      - '8010:8000'
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    env_file:
      - .env
    volumes:
      - ./data/db:/var/lib/postgresql/data
    restart: always
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_DB=${DATABASES_NAME}"
      - "POSTGRES_USER=${DATABASES_USER}"
      - "POSTGRES_PASSWORD=${DATABASES_PASSWORD}"
