networks:
  direct_net:
    external: true

services:
  tests:
    build:
      context: ./
      dockerfile: tests.Dockerfile
    command: bash -c 'python3 manage.py test'
    volumes:
      - .:/home/user/web
    restart: always
    networks:
      - direct_net
