[http.middlewares.simpleAuth.basicAuth]
  users = [
    "user:htpasswd_generate_secure_password"
  ]
[http.routers.api]
  rule = "Host(`monitor.DOMAIN.COM`)"
  entrypoints = ["websecure"]
  middlewares = ["simpleAuth"]
  service = "api@internal"
  [http.routers.api.tls]
    certResolver = "lets-encrypt"
