name: CI

on:
  push:
    branches: [ '**' ]

jobs:
  tests:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Run flake8
        run: docker compose -f docker-compose.tests.yml up --remove-orphans --exit-code-from flake8 flake8
      - name: Run tests
        run: docker compose -f docker-compose.tests.yml up --remove-orphans --exit-code-from tests tests
      - name: Delete containers
        run: docker compose -f docker-compose.tests.yml down
